services:
  - type: web
    name: driveahead-f1-analytics
    env: python
    plan: free
    rootDir: website
    buildCommand: pip install --upgrade pip && pip install --only-binary=all -r requirements.txt || pip install -r requirements.txt
    startCommand: python -m gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: FLASK_ENV
        value: production